fn main() -> Result<(), std::io::Error> {
    println!("{}", "Hello, World");
    Ok(())
}
